### ISSUE TITLE
io.github.nafg#slick-migration-api_2.11;0.4.2: not found

### ISSUE THREAD

**Issue by TommyEsteban** [nafg/slick-migration-api#18]
Trying to add dependency in build.sbt

"io.github.nafg" %% "slick-migration-api" % "0.4.2"

dependency cannot be found

resolver has been added
resolvers += Resolver.jcenterRepo

**Comment by nafg** [comment]
It should be there, see https://bintray.com/naftoligug/maven/slick-migration-api#files/io%2Fgithub%2Fnafg%2Fslick-migration-api_2.11%2F0.4.2. I was able to fetch it with coursier fetch -r https://jcenter.bintray.com io.github.nafg:slick-migration-api_2.11:0.4.2.

Can you post the full output of sbt?

**Comment by TommyEsteban** [comment]
Error:Error while importing SBT project:<br/>...<br/><pre>[info] Resolving org.scalactic#scalactic_2.11;3.0.1 ...
[info] Resolving com.softwaremill.macwire#macros_2.11;2.2.5 ...
[info] Resolving org.scala-lang#scala-compiler;2.11.8 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.4 ...
[info] Resolving jline#jline;2.12.1 ...
[info] Resolving com.lightbend.lagom#lagom-reloadable-server_2.11;1.4.0-M2 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: io.github.nafg#slick-migration-api_2.11;0.4.2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		io.github.nafg:slick-migration-api_2.11:0.4.2 (/home/tommy/projects/institution/build.sbt#L26)
[warn] 		  +- com.kariusdx:institution-impl_2.11:1.0-SNAPSHOT
[trace] Stack trace suppressed: run 'last institution-impl/*:ssExtractDependencies' for the full output.
[trace] Stack trace suppressed: run 'last institution-impl/*:update' for the full output.
[error] (institution-impl/*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: io.github.nafg#slick-migration-api_2.11;0.4.2: not found
[error] (institution-impl/*:update) sbt.ResolveException: unresolved dependency: io.github.nafg#slick-migration-api_2.11;0.4.2: not found
[error] Total time: 5 s, completed Dec 7, 2017 5:22:33 PM</pre><br/>See complete log in <a href="file:/home/tommy/.IdeaIC2017.1/system/log/sbt.last.log">file:/home/tommy/.IdeaIC2017.1/system/log/sbt.last.log</a>

**Comment by nafg** [comment]
That's not the full output. It should show a list of urls that it tried.

**Comment by TommyEsteban** [comment]
my sbt tries to solve the dependency with wrong location even the resolver is specified

==== public: tried
[warn]   https://repo1.maven.org/maven2/io/github/nafg/slick-migration-api_2.11/0.4.2/slick-migration-api_2.11-0.4.2.pom

**Comment by nafg** [comment]
Maven central is the only place it's looking?
Are you sure you added the resolver on the right project? Can you show your sbt config?

**Comment by i-dorofeev** [comment]
I had the same issue with this code:
```
libraryDependencies ++= {
  resolvers += Resolver.jcenterRepo
  Seq(
    "io.github.nafg" %% "slick-migration-api" % "0.4.2"
  )
}
```

When I moved addition of the resolver to the outer scope, it worked perfectly:
```
resolvers += Resolver.jcenterRepo
libraryDependencies ++= {
  Seq(
    "io.github.nafg" %% "slick-migration-api" % "0.4.2"
  )
}
```

**Comment by nafg** [comment]
@i-dorofeev that is because of how SBT works. Expressions like `+=` are not imperative commands that mutate SBT's state. They are just expressions that describe a desired change to its state. Therefore they have to be in a position that SBT can "collect" them, such as standalone lines in a `.sbt` file or parameters to the `.settings` method of a the project "builder."

Please read https://jazzy.id.au/2015/03/03/sbt-task-engine.html and https://jazzy.id.au/2015/03/04/sbt-declarative-dsl.html
