### ISSUE TITLE
Maven Artifacts missing?

### ISSUE THREAD

**Issue by aumann** [nafg/slick-migration-api#187]
Hey there,
is it possible that the maven central artifacts are missing? I can't resolve any of them.

I've tried (in scala 12):
``"io.github.nafg"         %% "slick-migration-api"            % "0.4.2"` and
``"io.github.nafg"         %% "slick-migration-api"            % "0.4.4"` and

I've only just tried this in a (quite dated) build, using _sbt 1.2.8_ and _scala 2.12_ - consequently, this might be an issue with my setup. 

Mostly opening this issue for asking "am I missing something, or are the artifacts indeed missing".

sbt output:
```
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/io/github/nafg/slick-migration-api_2.12/0.4.2/slick-migration-api_2.12-0.4.2.pom

[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/io/github/nafg/slick-migration-api_2.12/0.4.2/slick-migration-api_2.12-0.4.2.pom
######### ... some private repos here...
[warn] ==== Spring Plugins: tried
[warn]   https://repo.spring.io/plugins-release/io/github/nafg/slick-migration-api_2.12/0.4.2/slick-migration-api_2.12-0.4.2.pom
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/io/github/nafg/slick-migration-api_2.12/0.4.2/slick-migration-api_2.12-0.4.2.pom
```

**Comment by nafg** [comment]
That's a very old version. Try resolving it from JCenter.
