### ISSUE TITLE
Support for Slick 3.0.0

### ISSUE THREAD

**Issue by levinotik** [nafg/slick-migration-api#6]

**Comment by claytonsilva** [comment]
+1

**Comment by nafg** [comment]
You can now use 0.2.0 with slick 3.0.3 or 0.2.1 with slick 3.1.1
The artifacts are on bintray jcenter.

**Comment by nafg** [comment]
slick 3.0.3: `"io.github.nafg" %% "slick-migration-api" % "0.2.0"`
slick 3.1.1: `"io.github.nafg" %% "slick-migration-api" % "0.2.1"`

**Comment by nafg** [comment]
Mmm... seems @Romastyi changed the api a bit unnecessarily, I want to revert that so I plan to release 0.3.0 for slick 3.1.1, incompatible with 0.2.x.

Please let me know if I should do it for slick 3.0.x as well.

**Comment by nafg** [comment]
Released 0.3.0
