### ISSUE TITLE
License

### ISSUE THREAD

**Issue by malsharman** [nafg/slick-migration-api#7]
I was wondering what license you intended to use for this tool?

I would like to use it in one of the systems I'm working on but need to clarify this.

**Comment by rcoh** [comment]
+1

**Comment by gwils** [comment]
+1

**Comment by frossi85** [comment]
+1

**Comment by driverpt** [comment]
+1

**Comment by lastland** [comment]
How about Apache 2.0? It's quite flexible and it offers some protection against possible patent issues from future contributions.

**Comment by andreas-pabst** [comment]
+1

**Comment by ShaMSF** [comment]
+1

**Comment by p-andreas** [comment]
+1

**Comment by choffmeister** [comment]
Can this be considered done? https://github.com/nafg/slick-migration-api/blob/master/LICENSE is Apache 2.0 license.

**Comment by nafg** [comment]
Indeed!

Fixed in 3f630da in #34
