### ISSUE TITLE
Wrong 0.3.0 jar package?

### ISSUE THREAD

**Issue by lastland** [nafg/slick-migration-api#9]
Hi, I have been trying to integrate slick-migration-api 0.3.0 with my project. However, when using the trait `SqlMigration`, the compiler fails to find any method declared in the source code (e.g. `seq`, `actions`, `statements`). So I checked the jar package under `~/.ivy2`, and here's what I found by opening `SlickMigration.class` using `javap`:

```
public interface slick.migration.api.SqlMigration extends slick.migration.api.Migration {
  public abstract scala.collection.Seq<java.lang.String> sql();

  public abstract slick.jdbc.SimpleJdbcAction<scala.runtime.BoxedUnit> apply();
}
```

which seems to be the old `0.1.x` API, even though `MANIFEST.MF` shows that the version is 0.3.0.

Could there be anything wrong during the publish process?

**Comment by nafg** [comment]
The API wasn't supposed to change. The person who contributed slick 3
support changed it, I don't know why. I realized that after I published
0.2.x. The point of 0.3.0 was to revert the API. It still uses slick 3.

**Comment by lastland** [comment]
I see. This is confusing because the code in the master branch uses the 0.2.x changed API.

**Comment by lastland** [comment]
Would you mind pushing the 0.3.0 code to GitHub?

**Comment by nafg** [comment]
That's weird. I don't even know how it's possible since it publishes via Travis. I'll have to take a look...

**Comment by nafg** [comment]
Is this resolved?

**Comment by lastland** [comment]
Yes.
